"""empty message

Revision ID: 2252dd94a004
Revises: f43edfc18311
Create Date: 2021-06-14 10:48:13.536073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2252dd94a004'
down_revision = 'f43edfc18311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addcomment', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('addcomment', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addcomment', sa.Column('full_name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('addcomment', 'name')
    # ### end Alembic commands ###
