"""empty message

Revision ID: 30a5359c51b3
Revises: 3e12574d3210
Create Date: 2021-06-13 20:01:07.910128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a5359c51b3'
down_revision = '3e12574d3210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(length=100), nullable=True),
    sa.Column('short_description', sa.Text(length=80), nullable=False),
    sa.Column('description', sa.Text(length=80), nullable=False),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update')
    # ### end Alembic commands ###
