"""empty message

Revision ID: 36c1de23dd2e
Revises: 59077fb3840a
Create Date: 2021-06-16 16:06:07.372485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c1de23dd2e'
down_revision = '59077fb3840a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_description', sa.Text(length=80), nullable=False),
    sa.Column('date_time', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
