"""empty message

Revision ID: 418b2188be49
Revises: 60c5cbd7359b
Create Date: 2021-06-07 21:24:38.233123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418b2188be49'
down_revision = '60c5cbd7359b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profession', sa.Column('specialty', sa.String(length=20), nullable=False))
    op.drop_column('profession', 'sahe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profession', sa.Column('sahe', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('profession', 'specialty')
    # ### end Alembic commands ###
