"""empty message

Revision ID: 59077fb3840a
Revises: 3384a06be1c0
Create Date: 2021-06-16 10:20:17.601005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59077fb3840a'
down_revision = '3384a06be1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('images', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
