"""empty message

Revision ID: 60c5cbd7359b
Revises: 1c6511d97f3a
Create Date: 2021-06-07 21:11:01.218557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c5cbd7359b'
down_revision = '1c6511d97f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sahe', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profession')
    # ### end Alembic commands ###
