"""empty message

Revision ID: 84d89bbcbf2f
Revises: a34f9da09415
Create Date: 2021-06-16 08:53:07.121530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d89bbcbf2f'
down_revision = 'a34f9da09415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_description', sa.Text(length=80), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.Column('description2', sa.String(length=30), nullable=False),
    sa.Column('short_description2', sa.Text(length=80), nullable=False),
    sa.Column('description3', sa.String(length=30), nullable=False),
    sa.Column('description4', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
