"""empty message

Revision ID: ab508b920098
Revises: f8752b3392f5
Create Date: 2021-06-10 22:14:29.606928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab508b920098'
down_revision = 'f8752b3392f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('image', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'image')
    # ### end Alembic commands ###
