"""empty message

Revision ID: b6e4e17ebfd5
Revises: 30a5359c51b3
Create Date: 2021-06-14 08:44:20.881027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e4e17ebfd5'
down_revision = '30a5359c51b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('date_time', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addcomment')
    # ### end Alembic commands ###
