"""empty message

Revision ID: dd5a932b7ec7
Revises: bd40bff3cd17
Create Date: 2021-06-09 18:23:52.605855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5a932b7ec7'
down_revision = 'bd40bff3cd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patientcategory')
    op.drop_table('profession')
    op.drop_table('patient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('date_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.TEXT(length=80), nullable=False),
    sa.Column('image', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profession',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patientcategory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
