"""empty message

Revision ID: f43edfc18311
Revises: b6e4e17ebfd5
Create Date: 2021-06-14 09:01:06.012499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43edfc18311'
down_revision = 'b6e4e17ebfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addcomment', sa.Column('image', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addcomment', 'image')
    # ### end Alembic commands ###
